
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'About': typeof import("../../app/components/About.vue").default
  'BackIcon': typeof import("../../app/components/BackIcon.vue").default
  'BaseButton': typeof import("../../app/components/BaseButton.vue").default
  'BaseIcon': typeof import("../../app/components/BaseIcon.vue").default
  'BasePage': typeof import("../../app/components/BasePage.vue").default
  'BaseTable': typeof import("../../app/components/BaseTable.vue").default
  'Book': typeof import("../../app/components/Book.vue").default
  'ConflictNotice': typeof import("../../app/components/ConflictNotice.vue").default
  'ConflictNoticeText': typeof import("../../app/components/ConflictNoticeText.vue").default
  'EditAbleText': typeof import("../../app/components/EditAbleText.vue").default
  'Empty': typeof import("../../app/components/Empty.vue").default
  'Header': typeof import("../../app/components/Header.vue").default
  'Logo': typeof import("../../app/components/Logo.vue").default
  'MigrateDialog': typeof import("../../app/components/MigrateDialog.vue").default
  'Panel': typeof import("../../app/components/Panel.vue").default
  'PopConfirm': typeof import("../../app/components/PopConfirm.vue").default
  'PracticeLayout': typeof import("../../app/components/PracticeLayout.vue").default
  'ResourceCard': typeof import("../../app/components/ResourceCard.vue").default
  'Slide': typeof import("../../app/components/Slide.vue").default
  'StageProgress': typeof import("../../app/components/StageProgress.vue").default
  'WordItem': typeof import("../../app/components/WordItem.vue").default
  'ArticleAudio': typeof import("../../app/components/article/ArticleAudio.vue").default
  'EditArticle': typeof import("../../app/components/article/EditArticle.vue").default
  'EditBook': typeof import("../../app/components/article/EditBook.vue").default
  'EditSingleArticleModal': typeof import("../../app/components/article/EditSingleArticleModal.vue").default
  'QuestionForm': typeof import("../../app/components/article/QuestionForm.vue").default
  'QuestionItem': typeof import("../../app/components/article/QuestionItem.vue").default
  'Space': typeof import("../../app/components/article/Space.vue").default
  'TypingArticle': typeof import("../../app/components/article/TypingArticle.vue").default
  'TypingWord': typeof import("../../app/components/article/TypingWord.vue").default
  'Audio': typeof import("../../app/components/base/Audio.vue").default
  'BaseInput': typeof import("../../app/components/base/BaseInput.vue").default
  'Collapse': typeof import("../../app/components/base/Collapse.vue").default
  'InputNumber': typeof import("../../app/components/base/InputNumber.vue").default
  'Loading': typeof import("../../app/components/base/Loading.vue").default
  'OptionButton': typeof import("../../app/components/base/OptionButton.vue").default
  'Pagination': typeof import("../../app/components/base/Pagination.vue").default
  'Progress': typeof import("../../app/components/base/Progress.vue").default
  'Slider': typeof import("../../app/components/base/Slider.vue").default
  'Switch': typeof import("../../app/components/base/Switch.vue").default
  'Textarea': typeof import("../../app/components/base/Textarea.vue").default
  'Tooltip': typeof import("../../app/components/base/Tooltip.vue").default
  'Checkbox': typeof import("../../app/components/base/checkbox/Checkbox.vue").default
  'Form': typeof import("../../app/components/base/form/Form.vue").default
  'FormItem': typeof import("../../app/components/base/form/FormItem.vue").default
  'Types': typeof import("../../app/components/base/form/types").default
  'Radio': typeof import("../../app/components/base/radio/Radio.vue").default
  'RadioGroup': typeof import("../../app/components/base/radio/RadioGroup.vue").default
  'Option': typeof import("../../app/components/base/select/Option.vue").default
  'Select': typeof import("../../app/components/base/select/Select.vue").default
  'Toast': typeof import("../../app/components/base/toast/Toast").default
  'ToastComponent': typeof import("../../app/components/base/toast/ToastComponent.vue").default
  'Type': typeof import("../../app/components/base/toast/type").default
  'ChannelIcons': typeof import("../../app/components/channel-icons/ChannelIcons.vue").default
  'Github': typeof import("../../app/components/channel-icons/Github.vue").default
  'ShareIcon': typeof import("../../app/components/channel-icons/ShareIcon.vue").default
  'WeChat': typeof import("../../app/components/channel-icons/WeChat.vue").default
  'Dialog': typeof import("../../app/components/dialog/Dialog.vue").default
  'IeDialog': typeof import("../../app/components/dialog/IeDialog.vue").default
  'MiniDialog': typeof import("../../app/components/dialog/MiniDialog.vue").default
  'Close': typeof import("../../app/components/icon/Close.vue").default
  'DeleteIcon': typeof import("../../app/components/icon/DeleteIcon.vue").default
  'VolumeIcon': typeof import("../../app/components/icon/VolumeIcon.vue").default
  'ArticleList': typeof import("../../app/components/list/ArticleList.vue").default
  'BaseList': typeof import("../../app/components/list/BaseList.vue").default
  'DictGroup': typeof import("../../app/components/list/DictGroup.vue").default
  'DictList': typeof import("../../app/components/list/DictList.vue").default
  'List': typeof import("../../app/components/list/List.vue").default
  'WordList': typeof import("../../app/components/list/WordList.vue").default
  'ArticleSetting': typeof import("../../app/components/setting/ArticleSetting.vue").default
  'CommonSetting': typeof import("../../app/components/setting/CommonSetting.vue").default
  'Log': typeof import("../../app/components/setting/Log.vue").default
  'SettingDialog': typeof import("../../app/components/setting/SettingDialog.vue").default
  'SettingItem': typeof import("../../app/components/setting/SettingItem.vue").default
  'WordSetting': typeof import("../../app/components/setting/WordSetting.vue").default
  'SlideHorizontal': typeof import("../../app/components/slide/SlideHorizontal.vue").default
  'SlideItem': typeof import("../../app/components/slide/SlideItem.vue").default
  'Common': typeof import("../../app/components/slide/common").default
  'Data': typeof import("../../app/components/slide/data").default
  'Code': typeof import("../../app/components/user/Code.vue").default
  'Notice': typeof import("../../app/components/user/Notice.vue").default
  'ChangeLastPracticeIndexDialog': typeof import("../../app/components/word/ChangeLastPracticeIndexDialog.vue").default
  'Footer': typeof import("../../app/components/word/Footer.vue").default
  'GroupList': typeof import("../../app/components/word/GroupList.vue").default
  'PracticeSettingDialog': typeof import("../../app/components/word/PracticeSettingDialog.vue").default
  'PracticeWordListDialog': typeof import("../../app/components/word/PracticeWordListDialog.vue").default
  'SentenceHightLightWord': typeof import("../../app/components/word/SentenceHightLightWord.vue").default
  'ShufflePracticeSettingDialog': typeof import("../../app/components/word/ShufflePracticeSettingDialog.vue").default
  'Statistics': typeof import("../../app/components/word/Statistics.vue").default
  'TypeWord': typeof import("../../app/components/word/TypeWord.vue").default
  'VolumeSettingMiniDialog': typeof import("../../app/components/word/VolumeSettingMiniDialog.vue").default
  'UnoIcon': typeof import("../../../../node_modules/@unocss/nuxt/runtime/UnoIcon.vue").default
  'NuxtWelcome': typeof import("../../../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default
  'NuxtPicture': typeof import("../../../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default
  'NuxtLinkLocale': typeof import("../../../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default
  'SwitchLocalePathLink': typeof import("../../../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default
  'NuxtPage': typeof import("../../../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Body
  'NuxtIsland': typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyAbout': LazyComponent<typeof import("../../app/components/About.vue").default>
  'LazyBackIcon': LazyComponent<typeof import("../../app/components/BackIcon.vue").default>
  'LazyBaseButton': LazyComponent<typeof import("../../app/components/BaseButton.vue").default>
  'LazyBaseIcon': LazyComponent<typeof import("../../app/components/BaseIcon.vue").default>
  'LazyBasePage': LazyComponent<typeof import("../../app/components/BasePage.vue").default>
  'LazyBaseTable': LazyComponent<typeof import("../../app/components/BaseTable.vue").default>
  'LazyBook': LazyComponent<typeof import("../../app/components/Book.vue").default>
  'LazyConflictNotice': LazyComponent<typeof import("../../app/components/ConflictNotice.vue").default>
  'LazyConflictNoticeText': LazyComponent<typeof import("../../app/components/ConflictNoticeText.vue").default>
  'LazyEditAbleText': LazyComponent<typeof import("../../app/components/EditAbleText.vue").default>
  'LazyEmpty': LazyComponent<typeof import("../../app/components/Empty.vue").default>
  'LazyHeader': LazyComponent<typeof import("../../app/components/Header.vue").default>
  'LazyLogo': LazyComponent<typeof import("../../app/components/Logo.vue").default>
  'LazyMigrateDialog': LazyComponent<typeof import("../../app/components/MigrateDialog.vue").default>
  'LazyPanel': LazyComponent<typeof import("../../app/components/Panel.vue").default>
  'LazyPopConfirm': LazyComponent<typeof import("../../app/components/PopConfirm.vue").default>
  'LazyPracticeLayout': LazyComponent<typeof import("../../app/components/PracticeLayout.vue").default>
  'LazyResourceCard': LazyComponent<typeof import("../../app/components/ResourceCard.vue").default>
  'LazySlide': LazyComponent<typeof import("../../app/components/Slide.vue").default>
  'LazyStageProgress': LazyComponent<typeof import("../../app/components/StageProgress.vue").default>
  'LazyWordItem': LazyComponent<typeof import("../../app/components/WordItem.vue").default>
  'LazyArticleAudio': LazyComponent<typeof import("../../app/components/article/ArticleAudio.vue").default>
  'LazyEditArticle': LazyComponent<typeof import("../../app/components/article/EditArticle.vue").default>
  'LazyEditBook': LazyComponent<typeof import("../../app/components/article/EditBook.vue").default>
  'LazyEditSingleArticleModal': LazyComponent<typeof import("../../app/components/article/EditSingleArticleModal.vue").default>
  'LazyQuestionForm': LazyComponent<typeof import("../../app/components/article/QuestionForm.vue").default>
  'LazyQuestionItem': LazyComponent<typeof import("../../app/components/article/QuestionItem.vue").default>
  'LazySpace': LazyComponent<typeof import("../../app/components/article/Space.vue").default>
  'LazyTypingArticle': LazyComponent<typeof import("../../app/components/article/TypingArticle.vue").default>
  'LazyTypingWord': LazyComponent<typeof import("../../app/components/article/TypingWord.vue").default>
  'LazyAudio': LazyComponent<typeof import("../../app/components/base/Audio.vue").default>
  'LazyBaseInput': LazyComponent<typeof import("../../app/components/base/BaseInput.vue").default>
  'LazyCollapse': LazyComponent<typeof import("../../app/components/base/Collapse.vue").default>
  'LazyInputNumber': LazyComponent<typeof import("../../app/components/base/InputNumber.vue").default>
  'LazyLoading': LazyComponent<typeof import("../../app/components/base/Loading.vue").default>
  'LazyOptionButton': LazyComponent<typeof import("../../app/components/base/OptionButton.vue").default>
  'LazyPagination': LazyComponent<typeof import("../../app/components/base/Pagination.vue").default>
  'LazyProgress': LazyComponent<typeof import("../../app/components/base/Progress.vue").default>
  'LazySlider': LazyComponent<typeof import("../../app/components/base/Slider.vue").default>
  'LazySwitch': LazyComponent<typeof import("../../app/components/base/Switch.vue").default>
  'LazyTextarea': LazyComponent<typeof import("../../app/components/base/Textarea.vue").default>
  'LazyTooltip': LazyComponent<typeof import("../../app/components/base/Tooltip.vue").default>
  'LazyCheckbox': LazyComponent<typeof import("../../app/components/base/checkbox/Checkbox.vue").default>
  'LazyForm': LazyComponent<typeof import("../../app/components/base/form/Form.vue").default>
  'LazyFormItem': LazyComponent<typeof import("../../app/components/base/form/FormItem.vue").default>
  'LazyTypes': LazyComponent<typeof import("../../app/components/base/form/types").default>
  'LazyRadio': LazyComponent<typeof import("../../app/components/base/radio/Radio.vue").default>
  'LazyRadioGroup': LazyComponent<typeof import("../../app/components/base/radio/RadioGroup.vue").default>
  'LazyOption': LazyComponent<typeof import("../../app/components/base/select/Option.vue").default>
  'LazySelect': LazyComponent<typeof import("../../app/components/base/select/Select.vue").default>
  'LazyToast': LazyComponent<typeof import("../../app/components/base/toast/Toast").default>
  'LazyToastComponent': LazyComponent<typeof import("../../app/components/base/toast/ToastComponent.vue").default>
  'LazyType': LazyComponent<typeof import("../../app/components/base/toast/type").default>
  'LazyChannelIcons': LazyComponent<typeof import("../../app/components/channel-icons/ChannelIcons.vue").default>
  'LazyGithub': LazyComponent<typeof import("../../app/components/channel-icons/Github.vue").default>
  'LazyShareIcon': LazyComponent<typeof import("../../app/components/channel-icons/ShareIcon.vue").default>
  'LazyWeChat': LazyComponent<typeof import("../../app/components/channel-icons/WeChat.vue").default>
  'LazyDialog': LazyComponent<typeof import("../../app/components/dialog/Dialog.vue").default>
  'LazyIeDialog': LazyComponent<typeof import("../../app/components/dialog/IeDialog.vue").default>
  'LazyMiniDialog': LazyComponent<typeof import("../../app/components/dialog/MiniDialog.vue").default>
  'LazyClose': LazyComponent<typeof import("../../app/components/icon/Close.vue").default>
  'LazyDeleteIcon': LazyComponent<typeof import("../../app/components/icon/DeleteIcon.vue").default>
  'LazyVolumeIcon': LazyComponent<typeof import("../../app/components/icon/VolumeIcon.vue").default>
  'LazyArticleList': LazyComponent<typeof import("../../app/components/list/ArticleList.vue").default>
  'LazyBaseList': LazyComponent<typeof import("../../app/components/list/BaseList.vue").default>
  'LazyDictGroup': LazyComponent<typeof import("../../app/components/list/DictGroup.vue").default>
  'LazyDictList': LazyComponent<typeof import("../../app/components/list/DictList.vue").default>
  'LazyList': LazyComponent<typeof import("../../app/components/list/List.vue").default>
  'LazyWordList': LazyComponent<typeof import("../../app/components/list/WordList.vue").default>
  'LazyArticleSetting': LazyComponent<typeof import("../../app/components/setting/ArticleSetting.vue").default>
  'LazyCommonSetting': LazyComponent<typeof import("../../app/components/setting/CommonSetting.vue").default>
  'LazyLog': LazyComponent<typeof import("../../app/components/setting/Log.vue").default>
  'LazySettingDialog': LazyComponent<typeof import("../../app/components/setting/SettingDialog.vue").default>
  'LazySettingItem': LazyComponent<typeof import("../../app/components/setting/SettingItem.vue").default>
  'LazyWordSetting': LazyComponent<typeof import("../../app/components/setting/WordSetting.vue").default>
  'LazySlideHorizontal': LazyComponent<typeof import("../../app/components/slide/SlideHorizontal.vue").default>
  'LazySlideItem': LazyComponent<typeof import("../../app/components/slide/SlideItem.vue").default>
  'LazyCommon': LazyComponent<typeof import("../../app/components/slide/common").default>
  'LazyData': LazyComponent<typeof import("../../app/components/slide/data").default>
  'LazyCode': LazyComponent<typeof import("../../app/components/user/Code.vue").default>
  'LazyNotice': LazyComponent<typeof import("../../app/components/user/Notice.vue").default>
  'LazyChangeLastPracticeIndexDialog': LazyComponent<typeof import("../../app/components/word/ChangeLastPracticeIndexDialog.vue").default>
  'LazyFooter': LazyComponent<typeof import("../../app/components/word/Footer.vue").default>
  'LazyGroupList': LazyComponent<typeof import("../../app/components/word/GroupList.vue").default>
  'LazyPracticeSettingDialog': LazyComponent<typeof import("../../app/components/word/PracticeSettingDialog.vue").default>
  'LazyPracticeWordListDialog': LazyComponent<typeof import("../../app/components/word/PracticeWordListDialog.vue").default>
  'LazySentenceHightLightWord': LazyComponent<typeof import("../../app/components/word/SentenceHightLightWord.vue").default>
  'LazyShufflePracticeSettingDialog': LazyComponent<typeof import("../../app/components/word/ShufflePracticeSettingDialog.vue").default>
  'LazyStatistics': LazyComponent<typeof import("../../app/components/word/Statistics.vue").default>
  'LazyTypeWord': LazyComponent<typeof import("../../app/components/word/TypeWord.vue").default>
  'LazyVolumeSettingMiniDialog': LazyComponent<typeof import("../../app/components/word/VolumeSettingMiniDialog.vue").default>
  'LazyUnoIcon': LazyComponent<typeof import("../../../../node_modules/@unocss/nuxt/runtime/UnoIcon.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default>
  'LazyNuxtPicture': LazyComponent<typeof import("../../../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default>
  'LazyNuxtLinkLocale': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default>
  'LazySwitchLocalePathLink': LazyComponent<typeof import("../../../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default>
  'LazyNuxtPage': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazyNuxtIsland': LazyComponent<typeof import("../../../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
