// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/articles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/articles.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/_i18n/:hash/:locale/messages.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@netlify+blobs@9.1.2_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39_2aabd647664cd745dfd6f256dbb187ec/node_modules/@nuxtjs/i18n/dist/runtime/server/routes/messages').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+image@2.0.0_@netlify+blobs@9.1.2_db0@0.3.4_idb-keyval@6.2.2_ioredis@5.9.2_magicast@0.5.1/node_modules/@nuxt/image/dist/runtime/server/routes/_ipx').default>>>>
    }
  }
}
export {}