// Generated by auto imports
export {}
declare global {
  const createError: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.6_@types+node@22.19.7_@vue+compiler_2874b13bdd9c14b0496f10b196d95de5/node_modules/nuxt/dist/app/composables/error').createError
  const defineAppConfig: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.6_@types+node@22.19.7_@vue+compiler_2874b13bdd9c14b0496f10b196d95de5/node_modules/nuxt/dist/app/nuxt').defineAppConfig
  const defineI18nConfig: typeof import('../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@netlify+blobs@9.1.2_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39_2aabd647664cd745dfd6f256dbb187ec/node_modules/@nuxtjs/i18n/dist/runtime/composables/index').defineI18nConfig
  const defineI18nLocale: typeof import('../../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@netlify+blobs@9.1.2_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39_2aabd647664cd745dfd6f256dbb187ec/node_modules/@nuxtjs/i18n/dist/runtime/composables/index').defineI18nLocale
  const getRouteRules: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.6_@types+node@22.19.7_@vue+compiler_2874b13bdd9c14b0496f10b196d95de5/node_modules/nuxt/dist/app/composables/manifest').getRouteRules
  const setResponseStatus: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.6_@types+node@22.19.7_@vue+compiler_2874b13bdd9c14b0496f10b196d95de5/node_modules/nuxt/dist/app/composables/ssr').setResponseStatus
  const useAppConfig: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.6_@types+node@22.19.7_@vue+compiler_2874b13bdd9c14b0496f10b196d95de5/node_modules/nuxt/dist/app/config').useAppConfig
  const useEvent: typeof import('../../app/utils/eventBus').useEvent
  const useImage: typeof import('../../../../node_modules/.pnpm/@nuxt+image@2.0.0_@netlify+blobs@9.1.2_db0@0.3.4_idb-keyval@6.2.2_ioredis@5.9.2_magicast@0.5.1/node_modules/@nuxt/image/dist/runtime/composables').useImage
  const useRuntimeConfig: typeof import('../../../../node_modules/.pnpm/nuxt@4.3.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.6_@types+node@22.19.7_@vue+compiler_2874b13bdd9c14b0496f10b196d95de5/node_modules/nuxt/dist/app/nuxt').useRuntimeConfig
}