
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const About: typeof import("../app/components/About.vue").default
export const BackIcon: typeof import("../app/components/BackIcon.vue").default
export const BaseButton: typeof import("../app/components/BaseButton.vue").default
export const BaseIcon: typeof import("../app/components/BaseIcon.vue").default
export const BasePage: typeof import("../app/components/BasePage.vue").default
export const BaseTable: typeof import("../app/components/BaseTable.vue").default
export const Book: typeof import("../app/components/Book.vue").default
export const ConflictNotice: typeof import("../app/components/ConflictNotice.vue").default
export const ConflictNoticeText: typeof import("../app/components/ConflictNoticeText.vue").default
export const EditAbleText: typeof import("../app/components/EditAbleText.vue").default
export const Empty: typeof import("../app/components/Empty.vue").default
export const Header: typeof import("../app/components/Header.vue").default
export const Logo: typeof import("../app/components/Logo.vue").default
export const MigrateDialog: typeof import("../app/components/MigrateDialog.vue").default
export const Panel: typeof import("../app/components/Panel.vue").default
export const PopConfirm: typeof import("../app/components/PopConfirm.vue").default
export const PracticeLayout: typeof import("../app/components/PracticeLayout.vue").default
export const ResourceCard: typeof import("../app/components/ResourceCard.vue").default
export const Slide: typeof import("../app/components/Slide.vue").default
export const StageProgress: typeof import("../app/components/StageProgress.vue").default
export const WordItem: typeof import("../app/components/WordItem.vue").default
export const ArticleAudio: typeof import("../app/components/article/ArticleAudio.vue").default
export const EditArticle: typeof import("../app/components/article/EditArticle.vue").default
export const EditBook: typeof import("../app/components/article/EditBook.vue").default
export const EditSingleArticleModal: typeof import("../app/components/article/EditSingleArticleModal.vue").default
export const QuestionForm: typeof import("../app/components/article/QuestionForm.vue").default
export const QuestionItem: typeof import("../app/components/article/QuestionItem.vue").default
export const Space: typeof import("../app/components/article/Space.vue").default
export const TypingArticle: typeof import("../app/components/article/TypingArticle.vue").default
export const TypingWord: typeof import("../app/components/article/TypingWord.vue").default
export const Audio: typeof import("../app/components/base/Audio.vue").default
export const BaseInput: typeof import("../app/components/base/BaseInput.vue").default
export const Collapse: typeof import("../app/components/base/Collapse.vue").default
export const InputNumber: typeof import("../app/components/base/InputNumber.vue").default
export const Loading: typeof import("../app/components/base/Loading.vue").default
export const OptionButton: typeof import("../app/components/base/OptionButton.vue").default
export const Pagination: typeof import("../app/components/base/Pagination.vue").default
export const Progress: typeof import("../app/components/base/Progress.vue").default
export const Slider: typeof import("../app/components/base/Slider.vue").default
export const Switch: typeof import("../app/components/base/Switch.vue").default
export const Textarea: typeof import("../app/components/base/Textarea.vue").default
export const Tooltip: typeof import("../app/components/base/Tooltip.vue").default
export const Checkbox: typeof import("../app/components/base/checkbox/Checkbox.vue").default
export const Form: typeof import("../app/components/base/form/Form.vue").default
export const FormItem: typeof import("../app/components/base/form/FormItem.vue").default
export const Types: typeof import("../app/components/base/form/types").default
export const Radio: typeof import("../app/components/base/radio/Radio.vue").default
export const RadioGroup: typeof import("../app/components/base/radio/RadioGroup.vue").default
export const Option: typeof import("../app/components/base/select/Option.vue").default
export const Select: typeof import("../app/components/base/select/Select.vue").default
export const Toast: typeof import("../app/components/base/toast/Toast").default
export const ToastComponent: typeof import("../app/components/base/toast/ToastComponent.vue").default
export const Type: typeof import("../app/components/base/toast/type").default
export const ChannelIcons: typeof import("../app/components/channel-icons/ChannelIcons.vue").default
export const Github: typeof import("../app/components/channel-icons/Github.vue").default
export const ShareIcon: typeof import("../app/components/channel-icons/ShareIcon.vue").default
export const WeChat: typeof import("../app/components/channel-icons/WeChat.vue").default
export const Dialog: typeof import("../app/components/dialog/Dialog.vue").default
export const IeDialog: typeof import("../app/components/dialog/IeDialog.vue").default
export const MiniDialog: typeof import("../app/components/dialog/MiniDialog.vue").default
export const Close: typeof import("../app/components/icon/Close.vue").default
export const DeleteIcon: typeof import("../app/components/icon/DeleteIcon.vue").default
export const VolumeIcon: typeof import("../app/components/icon/VolumeIcon.vue").default
export const ArticleList: typeof import("../app/components/list/ArticleList.vue").default
export const BaseList: typeof import("../app/components/list/BaseList.vue").default
export const DictGroup: typeof import("../app/components/list/DictGroup.vue").default
export const DictList: typeof import("../app/components/list/DictList.vue").default
export const List: typeof import("../app/components/list/List.vue").default
export const WordList: typeof import("../app/components/list/WordList.vue").default
export const ArticleSetting: typeof import("../app/components/setting/ArticleSetting.vue").default
export const CommonSetting: typeof import("../app/components/setting/CommonSetting.vue").default
export const Log: typeof import("../app/components/setting/Log.vue").default
export const SettingDialog: typeof import("../app/components/setting/SettingDialog.vue").default
export const SettingItem: typeof import("../app/components/setting/SettingItem.vue").default
export const WordSetting: typeof import("../app/components/setting/WordSetting.vue").default
export const SlideHorizontal: typeof import("../app/components/slide/SlideHorizontal.vue").default
export const SlideItem: typeof import("../app/components/slide/SlideItem.vue").default
export const Common: typeof import("../app/components/slide/common").default
export const Data: typeof import("../app/components/slide/data").default
export const Code: typeof import("../app/components/user/Code.vue").default
export const Notice: typeof import("../app/components/user/Notice.vue").default
export const ChangeLastPracticeIndexDialog: typeof import("../app/components/word/ChangeLastPracticeIndexDialog.vue").default
export const Footer: typeof import("../app/components/word/Footer.vue").default
export const GroupList: typeof import("../app/components/word/GroupList.vue").default
export const PracticeSettingDialog: typeof import("../app/components/word/PracticeSettingDialog.vue").default
export const PracticeWordListDialog: typeof import("../app/components/word/PracticeWordListDialog.vue").default
export const SentenceHightLightWord: typeof import("../app/components/word/SentenceHightLightWord.vue").default
export const ShufflePracticeSettingDialog: typeof import("../app/components/word/ShufflePracticeSettingDialog.vue").default
export const Statistics: typeof import("../app/components/word/Statistics.vue").default
export const TypeWord: typeof import("../app/components/word/TypeWord.vue").default
export const VolumeSettingMiniDialog: typeof import("../app/components/word/VolumeSettingMiniDialog.vue").default
export const UnoIcon: typeof import("../../../node_modules/@unocss/nuxt/runtime/UnoIcon.vue").default
export const NuxtWelcome: typeof import("../../../node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../../../node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../../../node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default
export const NuxtPicture: typeof import("../../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default
export const NuxtLinkLocale: typeof import("../../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default
export const SwitchLocalePathLink: typeof import("../../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default
export const NuxtPage: typeof import("../../../node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Body
export const NuxtIsland: typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyAbout: LazyComponent<typeof import("../app/components/About.vue").default>
export const LazyBackIcon: LazyComponent<typeof import("../app/components/BackIcon.vue").default>
export const LazyBaseButton: LazyComponent<typeof import("../app/components/BaseButton.vue").default>
export const LazyBaseIcon: LazyComponent<typeof import("../app/components/BaseIcon.vue").default>
export const LazyBasePage: LazyComponent<typeof import("../app/components/BasePage.vue").default>
export const LazyBaseTable: LazyComponent<typeof import("../app/components/BaseTable.vue").default>
export const LazyBook: LazyComponent<typeof import("../app/components/Book.vue").default>
export const LazyConflictNotice: LazyComponent<typeof import("../app/components/ConflictNotice.vue").default>
export const LazyConflictNoticeText: LazyComponent<typeof import("../app/components/ConflictNoticeText.vue").default>
export const LazyEditAbleText: LazyComponent<typeof import("../app/components/EditAbleText.vue").default>
export const LazyEmpty: LazyComponent<typeof import("../app/components/Empty.vue").default>
export const LazyHeader: LazyComponent<typeof import("../app/components/Header.vue").default>
export const LazyLogo: LazyComponent<typeof import("../app/components/Logo.vue").default>
export const LazyMigrateDialog: LazyComponent<typeof import("../app/components/MigrateDialog.vue").default>
export const LazyPanel: LazyComponent<typeof import("../app/components/Panel.vue").default>
export const LazyPopConfirm: LazyComponent<typeof import("../app/components/PopConfirm.vue").default>
export const LazyPracticeLayout: LazyComponent<typeof import("../app/components/PracticeLayout.vue").default>
export const LazyResourceCard: LazyComponent<typeof import("../app/components/ResourceCard.vue").default>
export const LazySlide: LazyComponent<typeof import("../app/components/Slide.vue").default>
export const LazyStageProgress: LazyComponent<typeof import("../app/components/StageProgress.vue").default>
export const LazyWordItem: LazyComponent<typeof import("../app/components/WordItem.vue").default>
export const LazyArticleAudio: LazyComponent<typeof import("../app/components/article/ArticleAudio.vue").default>
export const LazyEditArticle: LazyComponent<typeof import("../app/components/article/EditArticle.vue").default>
export const LazyEditBook: LazyComponent<typeof import("../app/components/article/EditBook.vue").default>
export const LazyEditSingleArticleModal: LazyComponent<typeof import("../app/components/article/EditSingleArticleModal.vue").default>
export const LazyQuestionForm: LazyComponent<typeof import("../app/components/article/QuestionForm.vue").default>
export const LazyQuestionItem: LazyComponent<typeof import("../app/components/article/QuestionItem.vue").default>
export const LazySpace: LazyComponent<typeof import("../app/components/article/Space.vue").default>
export const LazyTypingArticle: LazyComponent<typeof import("../app/components/article/TypingArticle.vue").default>
export const LazyTypingWord: LazyComponent<typeof import("../app/components/article/TypingWord.vue").default>
export const LazyAudio: LazyComponent<typeof import("../app/components/base/Audio.vue").default>
export const LazyBaseInput: LazyComponent<typeof import("../app/components/base/BaseInput.vue").default>
export const LazyCollapse: LazyComponent<typeof import("../app/components/base/Collapse.vue").default>
export const LazyInputNumber: LazyComponent<typeof import("../app/components/base/InputNumber.vue").default>
export const LazyLoading: LazyComponent<typeof import("../app/components/base/Loading.vue").default>
export const LazyOptionButton: LazyComponent<typeof import("../app/components/base/OptionButton.vue").default>
export const LazyPagination: LazyComponent<typeof import("../app/components/base/Pagination.vue").default>
export const LazyProgress: LazyComponent<typeof import("../app/components/base/Progress.vue").default>
export const LazySlider: LazyComponent<typeof import("../app/components/base/Slider.vue").default>
export const LazySwitch: LazyComponent<typeof import("../app/components/base/Switch.vue").default>
export const LazyTextarea: LazyComponent<typeof import("../app/components/base/Textarea.vue").default>
export const LazyTooltip: LazyComponent<typeof import("../app/components/base/Tooltip.vue").default>
export const LazyCheckbox: LazyComponent<typeof import("../app/components/base/checkbox/Checkbox.vue").default>
export const LazyForm: LazyComponent<typeof import("../app/components/base/form/Form.vue").default>
export const LazyFormItem: LazyComponent<typeof import("../app/components/base/form/FormItem.vue").default>
export const LazyTypes: LazyComponent<typeof import("../app/components/base/form/types").default>
export const LazyRadio: LazyComponent<typeof import("../app/components/base/radio/Radio.vue").default>
export const LazyRadioGroup: LazyComponent<typeof import("../app/components/base/radio/RadioGroup.vue").default>
export const LazyOption: LazyComponent<typeof import("../app/components/base/select/Option.vue").default>
export const LazySelect: LazyComponent<typeof import("../app/components/base/select/Select.vue").default>
export const LazyToast: LazyComponent<typeof import("../app/components/base/toast/Toast").default>
export const LazyToastComponent: LazyComponent<typeof import("../app/components/base/toast/ToastComponent.vue").default>
export const LazyType: LazyComponent<typeof import("../app/components/base/toast/type").default>
export const LazyChannelIcons: LazyComponent<typeof import("../app/components/channel-icons/ChannelIcons.vue").default>
export const LazyGithub: LazyComponent<typeof import("../app/components/channel-icons/Github.vue").default>
export const LazyShareIcon: LazyComponent<typeof import("../app/components/channel-icons/ShareIcon.vue").default>
export const LazyWeChat: LazyComponent<typeof import("../app/components/channel-icons/WeChat.vue").default>
export const LazyDialog: LazyComponent<typeof import("../app/components/dialog/Dialog.vue").default>
export const LazyIeDialog: LazyComponent<typeof import("../app/components/dialog/IeDialog.vue").default>
export const LazyMiniDialog: LazyComponent<typeof import("../app/components/dialog/MiniDialog.vue").default>
export const LazyClose: LazyComponent<typeof import("../app/components/icon/Close.vue").default>
export const LazyDeleteIcon: LazyComponent<typeof import("../app/components/icon/DeleteIcon.vue").default>
export const LazyVolumeIcon: LazyComponent<typeof import("../app/components/icon/VolumeIcon.vue").default>
export const LazyArticleList: LazyComponent<typeof import("../app/components/list/ArticleList.vue").default>
export const LazyBaseList: LazyComponent<typeof import("../app/components/list/BaseList.vue").default>
export const LazyDictGroup: LazyComponent<typeof import("../app/components/list/DictGroup.vue").default>
export const LazyDictList: LazyComponent<typeof import("../app/components/list/DictList.vue").default>
export const LazyList: LazyComponent<typeof import("../app/components/list/List.vue").default>
export const LazyWordList: LazyComponent<typeof import("../app/components/list/WordList.vue").default>
export const LazyArticleSetting: LazyComponent<typeof import("../app/components/setting/ArticleSetting.vue").default>
export const LazyCommonSetting: LazyComponent<typeof import("../app/components/setting/CommonSetting.vue").default>
export const LazyLog: LazyComponent<typeof import("../app/components/setting/Log.vue").default>
export const LazySettingDialog: LazyComponent<typeof import("../app/components/setting/SettingDialog.vue").default>
export const LazySettingItem: LazyComponent<typeof import("../app/components/setting/SettingItem.vue").default>
export const LazyWordSetting: LazyComponent<typeof import("../app/components/setting/WordSetting.vue").default>
export const LazySlideHorizontal: LazyComponent<typeof import("../app/components/slide/SlideHorizontal.vue").default>
export const LazySlideItem: LazyComponent<typeof import("../app/components/slide/SlideItem.vue").default>
export const LazyCommon: LazyComponent<typeof import("../app/components/slide/common").default>
export const LazyData: LazyComponent<typeof import("../app/components/slide/data").default>
export const LazyCode: LazyComponent<typeof import("../app/components/user/Code.vue").default>
export const LazyNotice: LazyComponent<typeof import("../app/components/user/Notice.vue").default>
export const LazyChangeLastPracticeIndexDialog: LazyComponent<typeof import("../app/components/word/ChangeLastPracticeIndexDialog.vue").default>
export const LazyFooter: LazyComponent<typeof import("../app/components/word/Footer.vue").default>
export const LazyGroupList: LazyComponent<typeof import("../app/components/word/GroupList.vue").default>
export const LazyPracticeSettingDialog: LazyComponent<typeof import("../app/components/word/PracticeSettingDialog.vue").default>
export const LazyPracticeWordListDialog: LazyComponent<typeof import("../app/components/word/PracticeWordListDialog.vue").default>
export const LazySentenceHightLightWord: LazyComponent<typeof import("../app/components/word/SentenceHightLightWord.vue").default>
export const LazyShufflePracticeSettingDialog: LazyComponent<typeof import("../app/components/word/ShufflePracticeSettingDialog.vue").default>
export const LazyStatistics: LazyComponent<typeof import("../app/components/word/Statistics.vue").default>
export const LazyTypeWord: LazyComponent<typeof import("../app/components/word/TypeWord.vue").default>
export const LazyVolumeSettingMiniDialog: LazyComponent<typeof import("../app/components/word/VolumeSettingMiniDialog.vue").default>
export const LazyUnoIcon: LazyComponent<typeof import("../../../node_modules/@unocss/nuxt/runtime/UnoIcon.vue").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue").default>
export const LazyNuxtPicture: LazyComponent<typeof import("../../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue").default>
export const LazyNuxtLinkLocale: LazyComponent<typeof import("../../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale").default>
export const LazySwitchLocalePathLink: LazyComponent<typeof import("../../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink").default>
export const LazyNuxtPage: LazyComponent<typeof import("../../../node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../../../node_modules/nuxt/dist/head/runtime/components").Body>
export const LazyNuxtIsland: LazyComponent<typeof import("../../../node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
