export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { useRouteBaseName, useLocalePath, useLocaleRoute, useSwitchLocalePath, useLocaleHead, useBrowserLocale, useCookieLocale, useSetI18nParams, useI18nPreloadKeys, defineI18nRoute, defineI18nLocale, defineI18nConfig } from '../../../node_modules/.pnpm/@nuxtjs+i18n@10.2.1_@netlify+blobs@9.1.2_@vue+compiler-dom@3.5.27_db0@0.3.4_eslint@9.39_2aabd647664cd745dfd6f256dbb187ec/node_modules/@nuxtjs/i18n/dist/runtime/composables/index';
export { definePageMeta } from '../../../node_modules/.pnpm/nuxt@4.3.0_@netlify+blobs@9.1.2_@parcel+watcher@2.5.6_@types+node@22.19.7_@vue+compiler_2874b13bdd9c14b0496f10b196d95de5/node_modules/nuxt/dist/pages/runtime/composables';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useInit } from '../app/composables/useInit';
export { MessageBox, MessageBox } from '../app/utils/MessageBox';
export { PRACTICE_WORD_CACHE, PRACTICE_ARTICLE_CACHE, getPracticeWordCache, getPracticeArticleCache, setPracticeWordCache, setPracticeArticleCache, PracticeWordCache, PracticeArticleCache } from '../app/utils/cache';
export { useClientStorage, useClientLocalStorage } from '../app/utils/client-storage';
export { TOKEN_KEY, SAVE_DICT_KEY, SAVE_SETTING_KEY, APP_VERSION, LOCAL_FILE_KEY, DICT_LIST, SoundFileOptions, TourConfig } from '../app/utils/constants';
export { emitter, EventKey, useEvent, useEvents } from '../app/utils/eventBus';
export { default as gm } from '../app/utils/gm';
export { default as http, axiosInstance, AxiosResponse } from '../app/utils/http';
export { no, checkAndUpgradeSaveDict, checkAndUpgradeSaveSetting, shakeCommonDict, isMobile, useNav, _dateFormat, msToHourMinute, msToMinute, _getAccomplishDays, _getAccomplishDate, _getStudyProgress, _nextTick, _copy, _parseLRC, sleep, _getDictDataByUrl, convertToWord, cloneDeep, shuffle, last, debounce, throttle, reverse, groupBy, getRandomN, splitIntoN, loadJsLib, total, resourceWrap, isNewUser, jump2Feedback } from '../app/utils/index';
export { validateEmail, validatePhone, codeRules, accountRules, emailRules, phoneRules, passwordRules } from '../app/utils/validation';
export { getDefaultBaseState, useBaseStore, BaseState } from '../app/stores/base';
export { usePracticeStore, PracticeState } from '../app/stores/practice';
export { useRuntimeStore, RuntimeState } from '../app/stores/runtime';
export { getDefaultSettingState, useSettingStore, SettingState } from '../app/stores/setting';
export { useUserStore } from '../app/stores/user';
export { defineStore, acceptHMRUpdate, usePinia, storeToRefs } from '../../../node_modules/.pnpm/@pinia+nuxt@0.11.3_magicast@0.5.1_pinia@3.0.4_typescript@5.9.3_vue@3.5.27_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/composables';
export { useI18n } from 'vue-i18n';
export { useImage } from '../../../node_modules/.pnpm/@nuxt+image@2.0.0_@netlify+blobs@9.1.2_db0@0.3.4_idb-keyval@6.2.2_ioredis@5.9.2_magicast@0.5.1/node_modules/@nuxt/image/dist/runtime/composables';
export { useNuxtDevTools } from '../../../node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools';